# Generator expressions
list_num = [2 * num for num in range(10)]
print(type(list_num))
print(list_num)
print('-' * 20)

obj_num = (num for num in range(6))
print(list(obj_num))
print(type(obj_num))
print('-' * 20)

obj_num = (num for num in range(6))
for num in obj_num:
    print(num)
print('-' * 20)

obj_num = (num for num in range(6))
print(next(obj_num))
print(next(obj_num))
print(next(obj_num))
print(next(obj_num))
print(next(obj_num))
print('-' * 20)

even_nums = (num for num in range(10) if num % 2 ==0)
print(list(even_nums))
print('-' * 20)

# Generator functions
def num_sequence(n):
    """Generate values from 0 to n."""
    i = 0
    while i < n:
        yield i  # they yield sequences of values using the keyword yield
        i += 1

result = num_sequence(5)
print(type(result))
for item in result:
    print(item)

# Create a list of strings
lannister = ['cersei', 'jaime', 'tywin', 'tyrion', 'joffrey']

# Define generator function get_lengths
def get_lengths(input_list):
    """Generator function that yields the
    length of the strings in input_list."""

    # Yield the length of a string
    for person in input_list:
        yield len(person)

# Print the values generated by get_lengths()
for value in get_lengths(lannister):
    print(value)